# Generated by Django 4.2.6 on 2023-10-25 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DENGLUZHUCE', '0003_游戏帖子_游戏帖子图片'),
    ]

    operations = [
        migrations.CreateModel(
            name='评论',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('发评时间', models.DateTimeField(auto_now=True)),
                ('点赞数', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('帖子', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='评论', to='DENGLUZHUCE.游戏帖子', verbose_name='游戏帖子')),
                ('评论人', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
        ),
    ]
