# Generated by Django 4.2.6 on 2024-03-07 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DENGLUZHUCE', '0005_评论_评论'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('aiid', models.AutoField(primary_key=True, serialize=False)),
                ('personality_text', models.TextField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_time', models.DateTimeField(auto_now_add=True)),
                ('chat_content', models.TextField()),
                ('mode', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DENGLUZHUCE.aimodel')),
            ],
        ),
    ]
