# Generated by Django 4.2.6 on 2024-03-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DENGLUZHUCE', '0007_aimodel_聊天记录'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='chat_vector_dict',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
