# Generated by Django 4.2.6 on 2024-03-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DENGLUZHUCE', '0010_aimodel_相似度阈值'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='相似度最高的键的数量',
            field=models.TextField(default='5'),
        ),
    ]
